image: node

before_script:
  - npm i -g @redocly/cli@latest
  - apt-get update && apt-get install -y curl
  - curl -sL https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64 -o /usr/local/bin/yq
  - chmod +x /usr/local/bin/yq
  - chmod +x ./rm-header.sh
  - chmod +x ./p2olinux/postman2openapi
  - apt-get install -y python3-pip
  - apt-get install -y python3-venv # Install Python virtual environment package

pages:
  script:
    - ./p2olinux/postman2openapi postman/Prometeus\ Accounting\ API.postman_collection.json > openapi.yml
    - ./rm-header.sh
    - python3 -m venv myenv # Create a Python virtual environment
    - source myenv/bin/activate # Activate the virtual environment
    - pip install pyyaml # Install pyyaml inside the virtual environment
    - python3 merge_yaml.py
    - redocly build-docs merged_openapi.yml --output=public/index.html
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
